CREATE CONFIGURATION my_dg_config AS PRIMARY DATABASE IS CDB1 CONNECT IDENTIFIER IS CDB1;
ADD DATABASE ORACLE_SID_STBY AS CONNECT IDENTIFIER IS ORACLE_SID_STBY MAINTAINED AS PHYSICAL;
ENABLE CONFIGURATION;
